###
GET http://localhost:8080/api/student

###
GET http://localhost:8080/api/student/university={{universityId}}

###
GET http://localhost:8080/api/student/university={{universityId}}/faculty={{facultyId}}

###
GET http://localhost:8080/api/student/university={{universityId}}/group={{groupId}}

###
POST http://localhost:8080/api/student
Content-Type: application/json

{
  "firstname": "John",
  "lastname": "Doe",
  "city": "Tashkent",
  "district": "Mirobod",
  "street": "U. Nosir",
  "groupId": 2,
  "subjectId": [8, 4, 2, 1, 6]
}

###
DELETE http://localhost:8080/api/student/id=1